import { serve } from "https://deno.land/std@0.223.0/http/server.ts";
import { createClient } from "jsr:@supabase/supabase-js@2.48.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS"
};

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") || "";
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "";
const PREP_BASE_URL = Deno.env.get("PREPBUSINESS_API_BASE_URL") || "";
const PREP_TOKEN = Deno.env.get("PREPBUSINESS_API_TOKEN") || "";
const PREP_INBOUNDS_PATH = Deno.env.get("PREPBUSINESS_INBOUNDS_PATH") || "/shipments/inbound";
const SYNC_MODE = (Deno.env.get("PREPBUSINESS_SYNC_MODE") || "manual").toLowerCase();

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

const DIRECT_ACTION = "direct_to_amazon";
const HOLD_ACTION = "hold_for_prep";

function jsonResponse(body: Record<string, unknown>, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" }
  });
}

function normalizeText(value: unknown) {
  return typeof value === "string" ? value.trim() : value ?? null;
}

function normalizeEmail(value: unknown) {
  const text = normalizeText(value);
  return typeof text === "string" ? text.toLowerCase() : text ?? null;
}

function isAutoGeneratedShipmentNote(value: unknown) {
  const text = String(normalizeText(value) || "");
  return /shipment\s+created\s+at/i.test(text);
}

function resolveClientNote(...sources: Array<Record<string, unknown> | null | undefined>) {
  const fields = [
    "client_note",
    "clientNote",
    "customer_note",
    "customerNote",
    "comment",
    "comments",
    "note",
    "notes"
  ];
  for (const source of sources) {
    if (!source) continue;
    for (const field of fields) {
      const value = normalizeText(source[field]);
      if (!value) continue;
      if (isAutoGeneratedShipmentNote(value)) continue;
      return value;
    }
  }
  return null;
}

function encodeRemainingAction(sendToFba: boolean) {
  return sendToFba ? DIRECT_ACTION : HOLD_ACTION;
}

function normalizeReceivingStatus(value: unknown) {
  const raw = String(normalizeText(value) || "").toLowerCase();
  if (!raw) return "submitted";
  const allowed = new Set(["draft", "submitted", "partial", "received", "processed", "cancelled"]);
  if (allowed.has(raw)) return raw;
  if (["cancel", "canceled", "void", "rejected"].includes(raw)) return "cancelled";
  if (["done", "completed", "complete"].includes(raw)) return "processed";
  if (["received_all", "delivered"].includes(raw)) return "received";
  if (["new", "created", "open", "pending"].includes(raw)) return "draft";
  if (["in_progress", "processing", "shipped", "in_transit"].includes(raw)) return "submitted";
  return "submitted";
}

function isMissingColumnError(error: any, column: string) {
  if (!error) return false;
  const needle = column.toLowerCase();
  const message = String(error.message || "").toLowerCase();
  const details = String(error.details || "").toLowerCase();
  const hint = String(error.hint || "").toLowerCase();
  return message.includes(needle) || details.includes(needle) || hint.includes(needle);
}

function isStockPairDuplicateError(error: any) {
  const code = String(error?.code || "").trim();
  const message = String(error?.message || "").toLowerCase();
  const details = String(error?.details || "").toLowerCase();
  return (
    code === "23505" ||
    message.includes("stock_items_company_sku_asin_key") ||
    details.includes("stock_items_company_sku_asin_key")
  );
}

async function resolveMerchantContext(payload: Record<string, unknown>) {
  const merchantId =
    normalizeText(payload.merchant_id) ||
    normalizeText(payload.merchantId) ||
    normalizeText((payload.merchant as Record<string, unknown> | null)?.id) ||
    null;
  const email =
    normalizeEmail(payload.email) ||
    normalizeEmail(payload.arbitrage_email) ||
    normalizeEmail(payload.arbitrageOneEmail) ||
    normalizeEmail(payload.prep_email) ||
    normalizeEmail(payload.prepBusinessEmail) ||
    null;

  if (merchantId) {
    const { data } = await supabase
      .from("prep_merchants")
      .select("*")
      .eq("merchant_id", merchantId)
      .maybeSingle();
    if (data) {
      return { merchantId, companyId: data.company_id, userId: data.user_id, mapping: data };
    }

    const { data: integrationByMerchant } = await supabase
      .from("prep_business_integrations")
      .select("*")
      .ilike("merchant_id", String(merchantId))
      .order("updated_at", { ascending: false })
      .limit(1)
      .maybeSingle();
    if (integrationByMerchant) {
      return {
        merchantId: integrationByMerchant.merchant_id || merchantId,
        companyId: integrationByMerchant.company_id,
        userId: integrationByMerchant.user_id,
        integration: integrationByMerchant
      };
    }
  }

  if (email) {
    const { data } = await supabase
      .from("prep_business_integrations")
      .select("*")
      .or(`email_arbitrage_one.ilike.${email},email_prep_business.ilike.${email}`)
      .order("updated_at", { ascending: false })
      .limit(1)
      .maybeSingle();
    if (data) {
      return {
        merchantId: data.merchant_id || merchantId,
        companyId: data.company_id,
        userId: data.user_id,
        integration: data
      };
    }
  }

  return { merchantId, companyId: null, userId: null };
}

async function ensureStockItem(companyId: string, userId: string | null, item: Record<string, unknown>) {
  let asin = normalizeText(item.asin);
  const sku = normalizeText(item.sku);
  const ean = normalizeText(item.ean);
  const desiredName =
    normalizeText(item.product_name) ||
    normalizeText(item.title) ||
    sku ||
    asin ||
    "Unknown product";

  const maybeUpdateName = async (row: Record<string, unknown> | null) => {
    if (!row?.id || !desiredName) return row;
    const currentName = normalizeText((row as any).name) || "";
    const isPlaceholder =
      !currentName ||
      currentName === (asin || "") ||
      currentName === (sku || "");
    if (!isPlaceholder || currentName === desiredName) return row;
    const { data: updated, error } = await supabase
      .from("stock_items")
      .update({ name: desiredName })
      .eq("id", String((row as any).id))
      .select("*")
      .single();
    if (error) return row;
    return (updated as Record<string, unknown>) || row;
  };

  const maybeHydrateIdentifiers = async (row: Record<string, unknown> | null) => {
    if (!row?.id) return row;
    const patch: Record<string, unknown> = {};
    if (!normalizeText((row as any).asin) && asin) patch.asin = asin;
    if (!normalizeText((row as any).sku) && sku) patch.sku = sku;
    if (!normalizeText((row as any).ean) && ean) patch.ean = ean;
    if (Object.keys(patch).length === 0) return row;
    const { data: updated, error } = await supabase
      .from("stock_items")
      .update(patch)
      .eq("id", String((row as any).id))
      .select("*")
      .single();
    if (error) return row;
    return (updated as Record<string, unknown>) || row;
  };

  const finalizeMatchedRow = async (row: Record<string, unknown> | null) => {
    const withName = await maybeUpdateName(row);
    return await maybeHydrateIdentifiers(withName as Record<string, unknown>);
  };

  const sameValueOrMissing = (left: unknown, right: unknown) => {
    const a = normalizeText(left);
    const b = normalizeText(right);
    if (!a || !b) return true;
    return String(a).trim().toUpperCase() === String(b).trim().toUpperCase();
  };

  const canReuseSkuRow = (row: Record<string, unknown> | null) =>
    !!row && sameValueOrMissing((row as any).asin, asin);

  const canReuseAsinRow = (row: Record<string, unknown> | null) =>
    !!row && sameValueOrMissing((row as any).sku, sku);

  if (asin && sku) {
    const { data: exactPair } = await supabase
      .from("stock_items")
      .select("*")
      .eq("company_id", companyId)
      .eq("asin", asin)
      .eq("sku", sku)
      .maybeSingle();
    if (exactPair) return await finalizeMatchedRow(exactPair as Record<string, unknown>);
  }

  if (sku) {
    const { data: bySku } = await supabase
      .from("stock_items")
      .select("*")
      .eq("company_id", companyId)
      .eq("sku", sku)
      .maybeSingle();
    if (canReuseSkuRow(bySku as Record<string, unknown> | null)) {
      return await finalizeMatchedRow(bySku as Record<string, unknown>);
    }
  }

  if (asin) {
    const { data: byAsin } = await supabase
      .from("stock_items")
      .select("*")
      .eq("company_id", companyId)
      .eq("asin", asin)
      .maybeSingle();
    if (canReuseAsinRow(byAsin as Record<string, unknown> | null)) {
      return await finalizeMatchedRow(byAsin as Record<string, unknown>);
    }
  }

  if (ean) {
    const { data: byEanRows } = await supabase
      .from("stock_items")
      .select("*")
      .eq("company_id", companyId)
      .eq("ean", ean)
      .order("created_at", { ascending: true })
      .limit(10);

    const eanCandidates = Array.isArray(byEanRows) ? byEanRows : [];
    const exactPairByEan = eanCandidates.find(
      (row) => sameValueOrMissing((row as any).asin, asin) && sameValueOrMissing((row as any).sku, sku)
    );
    if (exactPairByEan && (normalizeText((exactPairByEan as any).sku) || normalizeText((exactPairByEan as any).asin))) {
      return await finalizeMatchedRow(exactPairByEan as Record<string, unknown>);
    }

    const reusableBySku = eanCandidates.find((row) => {
      const rowSku = normalizeText((row as any).sku);
      if (!rowSku || !sku) return false;
      return String(rowSku).trim().toUpperCase() === String(sku).trim().toUpperCase() && canReuseSkuRow(row as Record<string, unknown>);
    });
    if (reusableBySku) {
      return await finalizeMatchedRow(reusableBySku as Record<string, unknown>);
    }

    const reusableByAsin = eanCandidates.find((row) => {
      const rowAsin = normalizeText((row as any).asin);
      if (!rowAsin || !asin) return false;
      return String(rowAsin).trim().toUpperCase() === String(asin).trim().toUpperCase() && canReuseAsinRow(row as Record<string, unknown>);
    });
    if (reusableByAsin) {
      return await finalizeMatchedRow(reusableByAsin as Record<string, unknown>);
    }

    if (!asin) {
      const asinCarrier = eanCandidates.find((row) => normalizeText((row as any).asin));
      if (asinCarrier) {
        asin = normalizeText((asinCarrier as any).asin);
      }
    }
  }

  const payload = {
    company_id: companyId,
    user_id: userId || null,
    asin,
    sku,
    ean,
    name: desiredName,
    qty: 0,
    created_at: new Date().toISOString()
  };

  const { data: created, error } = await supabase
    .from("stock_items")
    .insert(payload)
    .select()
    .single();
  if (error) {
    if (isStockPairDuplicateError(error)) {
      const { data: existingAfterConflict } = await supabase
        .from("stock_items")
        .select("*")
        .eq("company_id", companyId)
        .eq("asin", asin)
        .eq("sku", sku)
        .maybeSingle();
      if (existingAfterConflict) {
        return await finalizeMatchedRow(existingAfterConflict as Record<string, unknown>);
      }
    }
    throw error;
  }
  return created;
}

async function insertReceivingShipment(payload: Record<string, unknown>) {
  let attempt = { ...payload };
  const removable = [
    "warehouse_country",
    "tracking_ids",
    "fba_shipment_ids",
    "import_source",
    "import_source_ref",
    "import_tags",
    "fba_mode",
    "client_store_name",
    "boxes_count"
  ];
  for (let i = 0; i <= removable.length; i += 1) {
    const { data, error } = await supabase
      .from("receiving_shipments")
      .insert([attempt])
      .select()
      .single();
    if (!error) return data;
    const missing = removable.find((col) => isMissingColumnError(error, col));
    if (!missing) throw error;
    const { [missing]: _removed, ...rest } = attempt as Record<string, unknown>;
    attempt = rest;
  }
  throw new Error("Could not insert receiving shipment.");
}

async function insertReceivingItems(items: Array<Record<string, unknown>>) {
  if (!items.length) return;
  let attempt = items;
  const removable = ["send_to_fba", "fba_qty", "stock_item_id", "remaining_action", "asin", "ean"];
  for (let i = 0; i <= removable.length; i += 1) {
    const { error } = await supabase.from("receiving_items").insert(attempt);
    if (!error) return;
    const missing = removable.find((col) => isMissingColumnError(error, col));
    if (!missing) throw error;
    attempt = attempt.map((row) => {
      const next = { ...row };
      delete (next as Record<string, unknown>)[missing];
      return next;
    });
  }
  throw new Error("Could not insert receiving items.");
}

async function importInbound(payload: Record<string, unknown>) {
  const items = Array.isArray(payload.items) ? payload.items : Array.isArray(payload.lines) ? payload.lines : [];
  if (!items.length) {
    return { error: "Missing items to import." };
  }

  const sourceId =
    normalizeText(payload.inbound_id) ||
    normalizeText(payload.inboundId) ||
    normalizeText(payload.source_id) ||
    normalizeText(payload.sourceId) ||
    normalizeText(payload.id) ||
    null;
  if (sourceId) {
    const { data: existing } = await supabase
      .from("prep_business_imports")
      .select("id, payload")
      .eq("source_id", sourceId)
      .maybeSingle();
    if (existing) {
      const existingPayload =
        existing?.payload && typeof existing.payload === "object" && !Array.isArray(existing.payload)
          ? (existing.payload as Record<string, unknown>)
          : {};
      const existingItems = Array.isArray(existingPayload.items)
        ? (existingPayload.items as Array<Record<string, unknown>>)
        : Array.isArray(existingPayload.lines)
        ? (existingPayload.lines as Array<Record<string, unknown>>)
        : items.map((entry) => entry as Record<string, unknown>);
      return {
        ok: true,
        idempotent: true,
        source_id: sourceId,
        products: summarizeInboundProducts(existingItems)
      };
    }
  }

  const { merchantId, companyId, userId, mapping, integration } = await resolveMerchantContext(payload);
  if (!companyId) {
    if (integration?.id) {
      await supabase
        .from("prep_business_integrations")
        .update({ status: "error", last_error: "Missing merchant/company mapping." })
        .eq("id", integration.id);
    }
    return { error: "Missing merchant mapping. Configure prep_merchants for this merchant." };
  }

  const resolvedItems = [];
  const skippedItems: Array<Record<string, unknown>> = [];
  for (const item of items) {
    const normalizedItem = normalizeInboundItem(item as Record<string, unknown>);
    const stock = await ensureStockItem(companyId, userId, normalizedItem);
    const resolvedAsin = normalizeText(normalizedItem.asin) || normalizeText(stock?.asin) || null;
    const resolvedSku = normalizeText(normalizedItem.sku) || normalizeText(stock?.sku) || null;
    const resolvedEan = normalizeText(normalizedItem.ean) || normalizeText(stock?.ean) || null;
    if (!resolvedAsin || !resolvedSku) {
      skippedItems.push({
        product_name:
          normalizeText(normalizedItem.product_name) ||
          normalizeText(normalizedItem.title) ||
          resolvedSku ||
          resolvedAsin ||
          "Unknown product",
        asin: resolvedAsin,
        sku: resolvedSku,
        ean: resolvedEan
      });
      continue;
    }
    resolvedItems.push({
      ...normalizedItem,
      stock_item_id: stock?.id || null,
      product_name:
        normalizeText(normalizedItem.product_name) ||
        stock?.name ||
        resolvedSku ||
        resolvedAsin,
      asin: resolvedAsin,
      sku: resolvedSku,
      ean: resolvedEan
    });
  }

  if (!resolvedItems.length) {
    return {
      error: "PrepBusiness inbound skipped because no line had both ASIN and SKU after sync.",
      source_id: sourceId,
      products: summarizeInboundProducts(items.map((entry) => entry as Record<string, unknown>)),
      skipped_items: skippedItems
    };
  }

  const destinationCountry =
    normalizeText(payload.destination_country) ||
    normalizeText(payload.destinationCountry) ||
    mapping?.destination_country ||
    "FR";
  const warehouseCountry =
    normalizeText(payload.warehouse_country) ||
    normalizeText(payload.warehouseCountry) ||
    mapping?.warehouse_country ||
    destinationCountry ||
    "FR";
  const trackingIds = Array.isArray(payload.tracking_ids) ? payload.tracking_ids : null;
  const fbaShipmentIds = Array.isArray(payload.fba_shipment_ids) ? payload.fba_shipment_ids : null;

  const header = await insertReceivingShipment({
    user_id: userId,
    company_id: companyId,
    status: normalizeReceivingStatus(payload.status),
    created_at: new Date().toISOString(),
    destination_country: String(destinationCountry).toUpperCase(),
    warehouse_country: String(warehouseCountry).toUpperCase(),
    carrier: normalizeText(payload.carrier) || null,
    carrier_other: normalizeText(payload.carrier_other) || null,
    tracking_id: normalizeText(payload.tracking_id) || (trackingIds?.[0] ?? null),
    tracking_ids: trackingIds,
    fba_shipment_ids: fbaShipmentIds,
    client_store_name:
      normalizeText(payload.client_store_name) ||
      normalizeText(payload.store_name) ||
      normalizeText(payload.name) ||
      normalizeText(payload.reference_id) ||
      null,
    boxes_count:
      Number(
        normalizeText(payload.boxes_count) ||
          normalizeText(payload.box_count) ||
          normalizeText(payload.cartons) ||
          normalizeText(payload.cartons_count) ||
          0
      ) || null,
    notes: resolveClientNote(payload),
    import_source: "prepbusiness",
    import_source_ref: sourceId,
    import_tags: mapping?.import_tags || null
  });

  const itemsPayload = resolvedItems.map((item: Record<string, unknown>, idx: number) => {
    const qtyRaw =
      Number(item.quantity ?? item.qty ?? item.units_requested ?? item.units ?? 0) || 0;
    const unitsRequested = Math.max(1, qtyRaw);
    const fbaQtyRaw = Number(item.fba_qty ?? unitsRequested) || 0;
    const sendToFba = Boolean(item.send_to_fba) && fbaQtyRaw > 0;
    const priceRaw = item.purchase_price;
    const purchasePrice = priceRaw === null || priceRaw === undefined || priceRaw === ""
      ? null
      : Number(String(priceRaw).replace(",", "."));
    return {
      shipment_id: header.id,
      line_number: idx + 1,
      ean_asin: normalizeText(item.ean) || normalizeText(item.asin) || normalizeText(item.sku) || "UNKNOWN",
      product_name: normalizeText(item.product_name) || normalizeText(item.title) || normalizeText(item.sku) || normalizeText(item.asin) || "Unknown product",
      asin: normalizeText(item.asin),
      sku: normalizeText(item.sku),
      ean: normalizeText(item.ean),
      purchase_price: Number.isFinite(purchasePrice) ? Number(purchasePrice.toFixed(2)) : null,
      quantity_received: unitsRequested,
      remaining_action: encodeRemainingAction(sendToFba),
      stock_item_id: item.stock_item_id || null,
      send_to_fba: sendToFba,
      fba_qty: sendToFba ? Math.max(0, fbaQtyRaw) : null
    };
  });

  await insertReceivingItems(itemsPayload);

  if (sourceId) {
    await supabase.from("prep_business_imports").insert({
      source_id: sourceId,
      merchant_id: merchantId,
      user_id: userId,
      company_id: companyId,
      receiving_shipment_id: header?.id || null,
      status: "imported",
      payload
    });
  }

  if (integration?.id) {
    await supabase
      .from("prep_business_integrations")
      .update({ status: "active", last_error: null, merchant_id: merchantId || integration.merchant_id, last_synced_at: new Date().toISOString() })
      .eq("id", integration.id);
  }

  return {
    ok: true,
    shipment_id: header?.id || null,
    source_id: sourceId,
    products: resolvedItems.map((item) => ({
      asin: normalizeText(item.asin) || null,
      sku: normalizeText(item.sku) || null
    }))
  };
}

function normalizeIdentifierType(value: unknown) {
  return String(value || "")
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9]/g, "");
}

function extractIdentifier(
  identifiers: Array<Record<string, unknown>> | undefined,
  types: string[]
) {
  if (!identifiers || !Array.isArray(identifiers)) return null;
  const allowed = new Set((types || []).map((t) => normalizeIdentifierType(t)));
  const hit = identifiers.find((row) => {
    const type = normalizeIdentifierType(row?.identifier_type);
    return allowed.has(type);
  });
  return normalizeText(hit?.identifier || null);
}

function mapInboundItems(items: Array<Record<string, unknown>>) {
  return items.map((row) => {
    const item = (row?.item as Record<string, unknown>) || {};
    const identifiers = Array.isArray(item?.identifiers) ? item.identifiers : [];
    const rawSku = normalizeText(row?.sku) || normalizeText(item?.merchant_sku) || null;
    const embeddedAsin = (() => {
      const match = String(rawSku || "").trim().toUpperCase().match(/(?:^|_)(B[0-9A-Z]{9})(?:$|_)/);
      return match?.[1] || null;
    })();
    const asin =
      normalizeText(row?.asin) ||
      normalizeText(item?.asin) ||
      extractIdentifier(identifiers, ["ASIN"]) ||
      embeddedAsin ||
      null;
    const ean =
      normalizeText(row?.ean) ||
      normalizeText(item?.ean) ||
      extractIdentifier(identifiers, ["EAN", "GTIN", "UPC"]) ||
      null;
    const sku = rawSku;
    const title = normalizeText(row?.title) || normalizeText(item?.title) || null;
    const expected = (row?.expected as Record<string, unknown>) || {};
    const qty = Number(row?.quantity ?? expected?.quantity ?? row?.qty ?? 0) || 0;
    return {
      item_id: normalizeText(row?.item_id) || normalizeText(item?.id) || null,
      asin,
      ean,
      sku,
      title,
      quantity: qty
    };
  });
}

function normalizeInboundItem(raw: Record<string, unknown>) {
  const nested = (raw?.item as Record<string, unknown>) || {};
  const identifiers = Array.isArray(nested?.identifiers)
    ? (nested.identifiers as Array<Record<string, unknown>>)
    : Array.isArray(raw?.identifiers)
    ? (raw.identifiers as Array<Record<string, unknown>>)
    : [];
  const asin =
    normalizeText(raw?.asin) ||
    normalizeText(nested?.asin) ||
    extractIdentifier(identifiers, ["ASIN"]) ||
    null;
  const ean =
    normalizeText(raw?.ean) ||
    normalizeText(nested?.ean) ||
    extractIdentifier(identifiers, ["EAN", "GTIN", "UPC"]) ||
    null;
  const sku =
    normalizeText(raw?.sku) ||
    normalizeText(raw?.merchant_sku) ||
    normalizeText(nested?.merchant_sku) ||
    normalizeText(nested?.sku) ||
    null;
  const title = normalizeText(raw?.title) || normalizeText(nested?.title) || null;
  const productName = normalizeText(raw?.product_name) || title || sku || asin || null;
  return {
    ...raw,
    asin,
    ean,
    sku,
    title,
    product_name: productName
  };
}

function summarizeInboundProducts(items: Array<Record<string, unknown>>) {
  const seen = new Set<string>();
  return (Array.isArray(items) ? items : [])
    .map((raw) => normalizeInboundItem(raw))
    .map((item) => ({
      asin: normalizeText(item.asin) || null,
      sku: normalizeText(item.sku) || null
    }))
    .filter((item) => item.asin || item.sku)
    .filter((item) => {
      const key = `${String(item.asin || "")}::${String(item.sku || "")}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });
}

async function fetchInboundItems(merchantId: string, shipmentId: string | number) {
  const base = PREP_BASE_URL.replace(/\/+$/, "");
  const url = `${base}/shipments/inbound/${shipmentId}/items`;
  const resp = await fetch(url, {
    headers: {
      Authorization: `Bearer ${PREP_TOKEN}`,
      "X-Api-Key": PREP_TOKEN,
      "X-Selected-Client-Id": String(merchantId),
      Accept: "application/json"
    }
  });
  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`PrepBusiness API error ${resp.status}: ${text || resp.statusText}`);
  }
  const data = await resp.json();
  if (Array.isArray(data?.items)) return data.items;
  if (Array.isArray(data?.data)) return data.data;
  return [];
}

function normalizeComparable(value: unknown) {
  return String(normalizeText(value) || "")
    .trim()
    .toUpperCase();
}

function normalizeLooseComparable(value: unknown) {
  return normalizeComparable(value).replace(/[^A-Z0-9]+/g, "");
}

function numbersEqual(left: unknown, right: unknown) {
  const a = Number(left);
  const b = Number(right);
  return Number.isFinite(a) && Number.isFinite(b) && a === b;
}

function getConfirmedReceivingQty(item: Record<string, unknown>) {
  const receivedUnits = Number(item?.received_units ?? 0);
  if (Number.isFinite(receivedUnits) && receivedUnits > 0) {
    return Math.max(0, Math.floor(receivedUnits));
  }
  const expectedUnits = Number(item?.quantity_received ?? 0);
  if (item?.is_received && Number.isFinite(expectedUnits) && expectedUnits > 0) {
    return Math.max(0, Math.floor(expectedUnits));
  }
  return 0;
}

function normalizePrepInboundItem(raw: Record<string, unknown>) {
  const normalized = normalizeInboundItem(raw);
  return {
    ...raw,
    ...normalized,
    shipment_item_id: raw?.id ?? null,
    item_id: raw?.item_id ?? (raw?.item as Record<string, unknown> | null)?.id ?? null,
    expected_quantity: Number((raw?.expected as Record<string, unknown> | null)?.quantity ?? 0) || 0,
    actual_quantity: Number((raw?.actual as Record<string, unknown> | null)?.quantity ?? 0) || 0,
    expected_item_group_configurations: Array.isArray((raw?.expected as Record<string, unknown> | null)?.item_group_configurations)
      ? (((raw?.expected as Record<string, unknown>).item_group_configurations as Array<Record<string, unknown>>))
      : [],
    actual_item_group_configurations: Array.isArray((raw?.actual as Record<string, unknown> | null)?.item_group_configurations)
      ? (((raw?.actual as Record<string, unknown>).item_group_configurations as Array<Record<string, unknown>>))
      : []
  };
}

function scoreInboundItemMatch(
  localItem: Record<string, unknown>,
  remoteItem: Record<string, unknown>,
  localIndex: number,
  remoteIndex: number
) {
  const localSku = normalizeComparable(localItem?.sku);
  const localAsin = normalizeComparable(localItem?.asin);
  const localEan = normalizeComparable(localItem?.ean || localItem?.ean_asin);
  const localName = normalizeLooseComparable(localItem?.product_name);
  const localQty = Number(localItem?.quantity_received ?? 0) || 0;

  const remoteSku = normalizeComparable(remoteItem?.sku);
  const remoteAsin = normalizeComparable(remoteItem?.asin);
  const remoteEan = normalizeComparable(remoteItem?.ean);
  const remoteName = normalizeLooseComparable(remoteItem?.product_name || remoteItem?.title);
  const remoteQty = Number(remoteItem?.expected_quantity ?? 0) || 0;

  if (localSku && remoteSku && localSku === remoteSku && localAsin && remoteAsin && localAsin === remoteAsin) {
    return 1000 + (numbersEqual(localQty, remoteQty) ? 50 : 0) - Math.abs(localIndex - remoteIndex);
  }
  if (localSku && remoteSku && localSku === remoteSku) {
    return 850 + (numbersEqual(localQty, remoteQty) ? 25 : 0) - Math.abs(localIndex - remoteIndex);
  }
  if (localAsin && remoteAsin && localAsin === remoteAsin) {
    return 800 + (numbersEqual(localQty, remoteQty) ? 25 : 0) - Math.abs(localIndex - remoteIndex);
  }
  if (localEan && remoteEan && localEan === remoteEan) {
    return 700 + (numbersEqual(localQty, remoteQty) ? 25 : 0) - Math.abs(localIndex - remoteIndex);
  }
  if (localName && remoteName && localName === remoteName) {
    return 500 + (numbersEqual(localQty, remoteQty) ? 25 : 0) - Math.abs(localIndex - remoteIndex);
  }
  if (numbersEqual(localQty, remoteQty) && localIndex === remoteIndex) {
    return 100;
  }
  return -1;
}

async function syncInboundReceivedQuantities({
  receivingShipmentId,
  merchantId,
  sourceId
}: {
  receivingShipmentId: string;
  merchantId: string;
  sourceId: string;
}) {
  const { data: localItems, error: localItemsError } = await supabase
    .from("receiving_items")
    .select("id, line_number, product_name, asin, sku, ean, ean_asin, quantity_received, received_units, is_received")
    .eq("shipment_id", receivingShipmentId)
    .order("line_number", { ascending: true });
  if (localItemsError) {
    throw new Error(`Failed to load receiving items: ${localItemsError.message || localItemsError}`);
  }

  const localConfirmedItems = (Array.isArray(localItems) ? localItems : [])
    .map((item) => ({
      ...item,
      confirmed_quantity: getConfirmedReceivingQty(item as Record<string, unknown>)
    }))
    .filter((item) => Number(item.confirmed_quantity || 0) > 0);

  if (!localConfirmedItems.length) {
    return { updated: 0, skipped: 0, unmatched: 0 };
  }

  const remoteItemsRaw = await fetchInboundItems(merchantId, sourceId);
  const remoteItems = (Array.isArray(remoteItemsRaw) ? remoteItemsRaw : []).map((item) =>
    normalizePrepInboundItem(item as Record<string, unknown>)
  );
  if (!remoteItems.length) {
    throw new Error("PrepBusiness inbound has no items to update.");
  }

  const usedRemoteIndexes = new Set<number>();
  const matches: Array<{ local: Record<string, unknown>; remote: Record<string, unknown> }> = [];
  const unmatched: Array<Record<string, unknown>> = [];

  localConfirmedItems.forEach((localItem, localIndex) => {
    let bestIndex = -1;
    let bestScore = -1;
    remoteItems.forEach((remoteItem, remoteIndex) => {
      if (usedRemoteIndexes.has(remoteIndex)) return;
      const score = scoreInboundItemMatch(localItem as Record<string, unknown>, remoteItem as Record<string, unknown>, localIndex, remoteIndex);
      if (score > bestScore) {
        bestScore = score;
        bestIndex = remoteIndex;
      }
    });
    if (bestIndex < 0 || bestScore < 0) {
      unmatched.push(localItem as Record<string, unknown>);
      return;
    }
    usedRemoteIndexes.add(bestIndex);
    matches.push({
      local: localItem as Record<string, unknown>,
      remote: remoteItems[bestIndex] as Record<string, unknown>
    });
  });

  if (unmatched.length > 0) {
    const labels = unmatched
      .map((item) => normalizeText(item.product_name) || normalizeText(item.sku) || normalizeText(item.asin) || String(item.id || "unknown"))
      .slice(0, 5)
      .join(", ");
    throw new Error(`Could not map ${unmatched.length} received line(s) to PrepBusiness inbound items: ${labels}`);
  }

  const base = PREP_BASE_URL.replace(/\/+$/, "");
  for (const { local, remote } of matches) {
    const itemId = Number(remote.item_id ?? 0) || Number((remote.item as Record<string, unknown> | null)?.id ?? 0) || 0;
    if (!itemId) {
      throw new Error(`PrepBusiness inbound item is missing item_id for line ${String(local.line_number || local.id || "")}`);
    }
    const expectedQuantity = Math.max(
      0,
      Number(remote.expected_quantity ?? local.quantity_received ?? local.confirmed_quantity ?? 0) || 0
    );
    const actualQuantity = Math.max(0, Number(local.confirmed_quantity ?? 0) || 0);
    const payload = {
      item_id: itemId,
      expected: [
        {
          quantity: expectedQuantity,
          item_group_configurations: Array.isArray(remote.expected_item_group_configurations)
            ? remote.expected_item_group_configurations
            : []
        }
      ],
      actual: [
        {
          quantity: actualQuantity,
          item_group_configurations: Array.isArray(remote.actual_item_group_configurations)
            ? remote.actual_item_group_configurations
            : []
        }
      ]
    };

    const resp = await fetch(`${base}/shipments/inbound/${sourceId}/update-item`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${PREP_TOKEN}`,
        "X-Api-Key": PREP_TOKEN,
        "X-Selected-Client-Id": String(merchantId),
        Accept: "application/json",
        "Content-Type": "application/json"
      },
      body: JSON.stringify(payload)
    });
    if (!resp.ok) {
      const text = await resp.text();
      throw new Error(`PrepBusiness update-item failed for item ${itemId}: ${resp.status} ${text || resp.statusText}`);
    }
  }

  return {
    updated: matches.length,
    skipped: localConfirmedItems.length - matches.length,
    unmatched: 0
  };
}

async function fetchInventoryItem(merchantId: string, itemId: string | number) {
  const base = PREP_BASE_URL.replace(/\/+$/, "");
  const url = `${base}/inventory/${itemId}`;
  const resp = await fetch(url, {
    headers: {
      Authorization: `Bearer ${PREP_TOKEN}`,
      "X-Api-Key": PREP_TOKEN,
      "X-Selected-Client-Id": String(merchantId),
      Accept: "application/json"
    }
  });
  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`PrepBusiness API error ${resp.status}: ${text || resp.statusText}`);
  }
  const data = await resp.json();
  return data?.item || data?.inventory_item || data?.data || data || null;
}

async function enrichInboundItemsFromInventory(
  merchantId: string,
  items: Array<Record<string, unknown>>
) {
  const cache = new Map<string, Record<string, unknown> | null>();
  const resolveInventoryDetails = async (itemId: string) => {
    if (cache.has(itemId)) return cache.get(itemId) || null;
    try {
      const data = await fetchInventoryItem(merchantId, itemId);
      const identifiers = Array.isArray(data?.identifiers) ? data.identifiers : [];
      const merchantSku =
        normalizeText(data?.merchant_sku) ||
        normalizeText(data?.sku) ||
        null;
      const embeddedAsin = (() => {
        const match = String(merchantSku || "").trim().toUpperCase().match(/(?:^|_)(B[0-9A-Z]{9})(?:$|_)/);
        return match?.[1] || null;
      })();
      const normalized = {
        asin:
          normalizeText(data?.asin) ||
          extractIdentifier(identifiers, ["ASIN"]) ||
          embeddedAsin ||
          null,
        ean:
          normalizeText(data?.ean) ||
          extractIdentifier(identifiers, ["EAN", "GTIN", "UPC"]) ||
          null,
        sku: merchantSku
      };
      cache.set(itemId, normalized);
      return normalized;
    } catch (error) {
      console.warn("PrepBusiness inventory item fetch failed", itemId, error?.message || error);
      cache.set(itemId, null);
      return null;
    }
  };

  const enriched = [];
  for (const item of Array.isArray(items) ? items : []) {
    const itemId = normalizeText(item?.item_id);
    if (!itemId || (normalizeText(item?.asin) && normalizeText(item?.sku))) {
      enriched.push(item);
      continue;
    }
    const details = await resolveInventoryDetails(String(itemId));
    enriched.push({
      ...item,
      asin: normalizeText(item?.asin) || normalizeText(details?.asin) || null,
      ean: normalizeText(item?.ean) || normalizeText(details?.ean) || null,
      sku: normalizeText(item?.sku) || normalizeText(details?.sku) || null
    });
  }
  return enriched;
}

async function fetchInboundDetails(merchantId: string, shipmentId: string | number) {
  const base = PREP_BASE_URL.replace(/\/+$/, "");
  const url = `${base}/shipments/inbound/${shipmentId}`;
  const resp = await fetch(url, {
    headers: {
      Authorization: `Bearer ${PREP_TOKEN}`,
      "X-Api-Key": PREP_TOKEN,
      "X-Selected-Client-Id": String(merchantId),
      Accept: "application/json"
    }
  });
  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`PrepBusiness API error ${resp.status}: ${text || resp.statusText}`);
  }
  const data = await resp.json();
  return data?.shipment || data;
}

async function fetchInbounds(merchantId: string, since: string | null) {
  const base = PREP_BASE_URL.replace(/\/+$/, "");
  const path = PREP_INBOUNDS_PATH.startsWith("/") ? PREP_INBOUNDS_PATH : `/${PREP_INBOUNDS_PATH}`;
  const params = new URLSearchParams();
  params.set("merchant_id", merchantId);
  if (since) params.set("updated_since", since);
  const url = `${base}${path}?${params.toString()}`;
  const resp = await fetch(url, {
    headers: {
      Authorization: `Bearer ${PREP_TOKEN}`,
      "X-Api-Key": PREP_TOKEN,
      "X-Selected-Client-Id": String(merchantId),
      Accept: "application/json"
    }
  });
  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`PrepBusiness API error ${resp.status}: ${text || resp.statusText}`);
  }
  const data = await resp.json();
  if (Array.isArray(data)) return data;
  if (Array.isArray(data?.items)) return data.items;
  if (Array.isArray(data?.data)) return data.data;
  if (Array.isArray(data?.inbounds)) return data.inbounds;
  return [];
}

async function syncPendingReceives() {
  const { data: imports, error: importsError } = await supabase
    .from("prep_business_imports")
    .select("id, source_id, merchant_id, receiving_shipment_id, status")
    .eq("status", "imported")
    .not("source_id", "is", null)
    .not("merchant_id", "is", null)
    .not("receiving_shipment_id", "is", null)
    .order("created_at", { ascending: true })
    .limit(200);
  if (importsError || !imports?.length) return [];

  const results: Array<Record<string, unknown>> = [];
  for (const row of imports) {
    const receivingShipmentId = normalizeText((row as any).receiving_shipment_id);
    const sourceId = normalizeText((row as any).source_id);
    const merchantId = normalizeText((row as any).merchant_id);
    if (!receivingShipmentId || !sourceId || !merchantId) continue;

    const { data: shipment, error: shipmentError } = await supabase
      .from("receiving_shipments")
      .select("status")
      .eq("id", receivingShipmentId)
      .maybeSingle();
    if (shipmentError || !shipment) continue;
    if (!["received", "processed"].includes(String(shipment.status || "").toLowerCase())) continue;

    let quantitySync;
    try {
      quantitySync = await syncInboundReceivedQuantities({
        receivingShipmentId,
        merchantId,
        sourceId
      });
    } catch (error) {
      results.push({
        error: `Receive quantity sync failed: ${error instanceof Error ? error.message : String(error)}`,
        source_id: sourceId,
        merchant_id: merchantId
      });
      continue;
    }

    const base = PREP_BASE_URL.replace(/\/+$/, "");
    const url = `${base}/shipments/inbound/${sourceId}/receive`;
    const resp = await fetch(url, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${PREP_TOKEN}`,
        "X-Api-Key": PREP_TOKEN,
        "X-Selected-Client-Id": String(merchantId),
        Accept: "application/json"
      }
    });

    if (!resp.ok) {
      const text = await resp.text();
      results.push({
        error: `Receive sync failed: PrepBusiness API error ${resp.status}: ${text || resp.statusText}`,
        source_id: sourceId,
        merchant_id: merchantId
      });
      continue;
    }

    await supabase
      .from("prep_business_imports")
      .update({ status: "received" })
      .eq("id", (row as any).id);
    results.push({
      ok: true,
      source_id: sourceId,
      merchant_id: merchantId,
      action: "receive-sync",
      quantity_sync: quantitySync
    });
  }
  return results;
}

async function handleSync(req: Request) {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  let body: Record<string, unknown> = {};
  if (req.method === "POST") {
    try {
      body = await req.json();
    } catch (_e) {
      return jsonResponse({ error: "Invalid JSON body" }, 400);
    }
  }

  if (req.method === "POST" && normalizeText(body.action) === "receive") {
    if (!PREP_BASE_URL || !PREP_TOKEN) {
      return jsonResponse({ error: "Missing PREPBUSINESS_API_BASE_URL or PREPBUSINESS_API_TOKEN." }, 400);
    }

    const receivingShipmentId = normalizeText(body.receiving_shipment_id) || normalizeText(body.receivingShipmentId);
    let sourceId = normalizeText(body.source_id) || normalizeText(body.sourceId);
    let merchantId = normalizeText(body.merchant_id) || normalizeText(body.merchantId);

    if (!sourceId || !merchantId) {
      if (!receivingShipmentId) {
        return jsonResponse({ error: "Missing receiving_shipment_id or source_id." }, 400);
      }
      const { data, error } = await supabase
        .from("prep_business_imports")
        .select("source_id, merchant_id, status")
        .eq("receiving_shipment_id", receivingShipmentId)
        .order("created_at", { ascending: false })
        .limit(1)
        .maybeSingle();
      if (error || !data) {
        return jsonResponse({ error: "No PrepBusiness import found for receiving_shipment_id." }, 404);
      }
      sourceId = sourceId || normalizeText(data.source_id);
      merchantId = merchantId || normalizeText(data.merchant_id);
    }

    if (!sourceId || !merchantId) {
      return jsonResponse({ error: "Missing source_id or merchant_id for PrepBusiness receive." }, 400);
    }

    const quantitySync = receivingShipmentId
      ? await syncInboundReceivedQuantities({
          receivingShipmentId,
          merchantId,
          sourceId
        })
      : { updated: 0, skipped: 0, unmatched: 0 };

    const base = PREP_BASE_URL.replace(/\/+$/, "");
    const url = `${base}/shipments/inbound/${sourceId}/receive`;
    const resp = await fetch(url, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${PREP_TOKEN}`,
        "X-Api-Key": PREP_TOKEN,
        "X-Selected-Client-Id": String(merchantId),
        Accept: "application/json"
      }
    });

    if (!resp.ok) {
      const text = await resp.text();
      return jsonResponse({ error: `PrepBusiness API error ${resp.status}: ${text || resp.statusText}` }, 502);
    }

    if (receivingShipmentId) {
      await supabase
        .from("prep_business_imports")
        .update({ status: "received" })
        .eq("receiving_shipment_id", receivingShipmentId);
    }

    return jsonResponse({ ok: true, source_id: sourceId, merchant_id: merchantId, quantity_sync: quantitySync });
  }

  if (req.method === "POST" && ["archive", "delete"].includes(String(normalizeText(body.action) || "").toLowerCase())) {
    if (!PREP_BASE_URL || !PREP_TOKEN) {
      return jsonResponse({ error: "Missing PREPBUSINESS_API_BASE_URL or PREPBUSINESS_API_TOKEN." }, 400);
    }

    const receivingShipmentId = normalizeText(body.receiving_shipment_id) || normalizeText(body.receivingShipmentId);
    let sourceId = normalizeText(body.source_id) || normalizeText(body.sourceId);
    let merchantId = normalizeText(body.merchant_id) || normalizeText(body.merchantId);

    if (!sourceId || !merchantId) {
      if (!receivingShipmentId) {
        return jsonResponse({ error: "Missing receiving_shipment_id or source_id." }, 400);
      }
      const { data, error } = await supabase
        .from("prep_business_imports")
        .select("source_id, merchant_id")
        .eq("receiving_shipment_id", receivingShipmentId)
        .order("created_at", { ascending: false })
        .limit(1)
        .maybeSingle();
      if (error || !data) {
        return jsonResponse({ error: "No PrepBusiness import found for receiving_shipment_id." }, 404);
      }
      sourceId = sourceId || normalizeText(data.source_id);
      merchantId = merchantId || normalizeText(data.merchant_id);
    }

    if (!sourceId || !merchantId) {
      return jsonResponse({ error: "Missing source_id or merchant_id for PrepBusiness archive." }, 400);
    }

    const numericSourceId = Number(sourceId);
    const shipmentIds = Number.isFinite(numericSourceId) ? [numericSourceId] : [sourceId];

    const base = PREP_BASE_URL.replace(/\/+$/, "");
    const url = `${base}/shipments/inbound/batch/archive`;
    const resp = await fetch(url, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${PREP_TOKEN}`,
        "X-Api-Key": PREP_TOKEN,
        "X-Selected-Client-Id": String(merchantId),
        Accept: "application/json",
        "Content-Type": "application/json"
      },
      body: JSON.stringify({ shipment_ids: shipmentIds })
    });

    if (!resp.ok) {
      const text = await resp.text();
      return jsonResponse({ error: `PrepBusiness API error ${resp.status}: ${text || resp.statusText}` }, 502);
    }

    await supabase
      .from("prep_business_imports")
      .update({ status: "archived" })
      .eq("source_id", sourceId);

    return jsonResponse({
      ok: true,
      action: "archive-sync",
      source_id: sourceId,
      merchant_id: merchantId
    });
  }

  const inbounds = Array.isArray(body.inbounds) ? body.inbounds : [];
  if (inbounds.length) {
    const results = [];
    for (const inbound of inbounds) {
      const result = await importInbound(inbound as Record<string, unknown>);
      results.push(result);
    }
    return jsonResponse({ ok: true, mode: "manual", imported: results.length, results });
  }

  if (SYNC_MODE !== "api") {
    return jsonResponse({
      error: "SYNC_MODE is not api. Provide inbounds[] in request body or set PREPBUSINESS_SYNC_MODE=api."
    }, 400);
  }

  if (!PREP_BASE_URL || !PREP_TOKEN) {
    return jsonResponse({ error: "Missing PREPBUSINESS_API_BASE_URL or PREPBUSINESS_API_TOKEN." }, 400);
  }

  const receiveSyncResults = await syncPendingReceives();

  const { data: merchants, error } = await supabase
    .from("prep_merchants")
    .select("*")
    .eq("sync_enabled", true);
  if (error) {
    return jsonResponse({ error: error.message || "Could not load prep_merchants." }, 500);
  }

  const { data: integrationMerchants, error: integrationMerchantsError } = await supabase
    .from("prep_business_integrations")
    .select("id, merchant_id, company_id, user_id, last_synced_at, status")
    .not("merchant_id", "is", null)
    .in("status", ["active", "mapped", "pending"]);
  if (integrationMerchantsError) {
    return jsonResponse(
      { error: integrationMerchantsError.message || "Could not load prep_business_integrations." },
      500
    );
  }

  const merchantMap = new Map<string, Record<string, unknown>>();
  for (const row of merchants || []) {
    const key = normalizeText((row as Record<string, unknown>).merchant_id);
    if (!key) continue;
    merchantMap.set(String(key), { ...(row as Record<string, unknown>) });
  }
  for (const row of integrationMerchants || []) {
    const merchantId = normalizeText((row as Record<string, unknown>).merchant_id);
    if (!merchantId) continue;
    if (!merchantMap.has(String(merchantId))) {
      merchantMap.set(String(merchantId), {
        merchant_id: merchantId,
        company_id: (row as Record<string, unknown>).company_id || null,
        user_id: (row as Record<string, unknown>).user_id || null,
        last_sync_at: (row as Record<string, unknown>).last_synced_at || null,
        integration_id: (row as Record<string, unknown>).id || null
      });
      continue;
    }
    const current = merchantMap.get(String(merchantId)) || {};
    merchantMap.set(String(merchantId), {
      ...current,
      integration_id: current.integration_id || (row as Record<string, unknown>).id || null,
      company_id: current.company_id || (row as Record<string, unknown>).company_id || null,
      user_id: current.user_id || (row as Record<string, unknown>).user_id || null,
      last_sync_at: current.last_sync_at || (row as Record<string, unknown>).last_synced_at || null
    });
  }

  const syncMerchants = Array.from(merchantMap.values());

  const results = [];
  for (const merchant of syncMerchants) {
    const since = merchant.last_sync_at ? String(merchant.last_sync_at) : null;
    if (!merchant.merchant_id) continue;

    let inboundList: Array<Record<string, unknown>> = [];
    try {
      inboundList = await fetchInbounds(String(merchant.merchant_id), since);
    } catch (error) {
      console.error("PrepBusiness inbounds fetch failed", merchant.merchant_id, error?.message || error);
      results.push({
        error: `Fetch inbounds failed: ${String(error?.message || error)}`,
        merchant_id: merchant.merchant_id
      });
      continue;
    }

    for (const inbound of inboundList) {
      const shipmentId = normalizeText((inbound as Record<string, unknown>)?.id || null);
      let items: Array<Record<string, unknown>> = [];
      let details: Record<string, unknown> | null = null;
      if (shipmentId) {
        try {
          const rawItems = await fetchInboundItems(String(merchant.merchant_id), shipmentId);
          items = await enrichInboundItemsFromInventory(
            String(merchant.merchant_id),
            mapInboundItems(rawItems as Array<Record<string, unknown>>)
          );
        } catch (error) {
          console.warn("PrepBusiness items fetch failed", shipmentId, error?.message || error);
        }
        try {
          details = await fetchInboundDetails(String(merchant.merchant_id), shipmentId) as Record<string, unknown>;
        } catch (error) {
          console.warn("PrepBusiness shipment fetch failed", shipmentId, error?.message || error);
        }
      }

      const trackingNumbers = Array.isArray((details as any)?.tracking_numbers)
        ? (details as any).tracking_numbers
        : [];
      const trackingIds = trackingNumbers
        .map((row: any) => normalizeText(row?.number))
        .filter(Boolean);
      const carrier = trackingNumbers.find((row: any) => normalizeText(row?.carrier))?.carrier || null;

      const payload = {
        ...(details || inbound),
        ...inbound,
        merchant_id: merchant.merchant_id,
        items,
        tracking_ids: trackingIds.length ? trackingIds : undefined,
        tracking_id: trackingIds.length ? trackingIds[0] : undefined,
        carrier: normalizeText((details as any)?.carrier) || normalizeText(carrier) || undefined,
        notes: resolveClientNote(details || null, inbound || null)
      };
      try {
        const result = await importInbound(payload as Record<string, unknown>);
        results.push(result);
      } catch (error) {
        console.error("PrepBusiness import failed", merchant.merchant_id, shipmentId, error?.message || error);
        results.push({
          error: `Import failed: ${String(error?.message || error)}`,
          merchant_id: merchant.merchant_id,
          source_id: shipmentId
        });
      }
    }

    if (merchant.id) {
      await supabase
        .from("prep_merchants")
        .update({ last_sync_at: new Date().toISOString() })
        .eq("id", merchant.id);
    }
    if (merchant.integration_id) {
      await supabase
        .from("prep_business_integrations")
        .update({ last_synced_at: new Date().toISOString() })
        .eq("id", merchant.integration_id);
    }
  }

  return jsonResponse({
    ok: true,
    mode: "api",
    imported: results.length,
    receive_synced: receiveSyncResults.length,
    receive_results: receiveSyncResults,
    results
  });
}

serve(handleSync);
