export const STEP1_COPY = {
  en: {
    opDefaultIssue: 'Amazon reported an issue for this SKU. Review and try again.',
    opMissingPrep: 'Prep classification is missing for this SKU. Choose prep and submit again.',
    opNotEligible: 'This product is currently not eligible for inbound on the selected marketplace.',
    validationMissingBoxes: 'Add at least one box for every pack with units.',
    validationMissingAssignments: 'Distribute all units into boxes (Assigned must equal Units).',
    validationMissingDims: 'Add dimensions and weight for every box.',
    validationEmptyBoxes: 'Some boxes are empty. Remove them or add items.',
    validationOverweight: 'Weight exceeds the {kg} kg limit.',
    validationOversize: 'A dimension exceeds the {cm} cm limit for a box that does not contain exactly 1 unit.',
    prepRequired: 'Prep required: {list}',
    prepSetNeeded: 'Prep set: Prep needed',
    prepSetNone: 'Prep set: No prep needed',
    statusEligible: 'Eligible',
    statusListingMissing: 'Listing missing',
    statusListingInactive: 'Listing inactive',
    statusRestricted: 'Restricted',
    statusUnknown: 'Unknown',
    statusReasonListingMissingDestination: 'Listing missing on destination marketplace',
    statusReasonListingDiscoverable: 'Listing found with status DISCOVERABLE (eligible)',
    readyToPack: 'Ready to pack',
    removeListing: 'Remove listing',
    noBoxesAssignedYet: 'No boxes assigned yet.',
    noServicesSelected: 'No services selected.',
    notEligibleBanner: 'Some products are not eligible for the selected marketplace.',
    inboundPlanNotReady: 'Amazon inbound plan is not ready. Retry Step 1 to regenerate the plan.',
    operationIssuesTitle: 'Amazon reported issues for some SKUs:',
    planStillLoading: 'Amazon plan is still loading. Waiting for generated SKUs/shipments; nothing to show yet.',
    ignoredLinesNotice: '{count} line(s) without SKU were ignored. Complete SKU on those lines if you want to include them.',
    noticeMissingSkuOnMarketplace: 'SKU missing listing on marketplace {marketplace} ({list}). Check if it exists as FBA.',
    completeBoxPlanning: 'Complete box planning before continuing.',
    noUnitsWarning: 'No units to send. Set at least 1 unit.',
    alertNotEligible: 'Some SKUs are not eligible on Amazon; fix eligibility and try again.',
    alertPlanNotReady: 'Amazon inbound plan is not ready. Retry Step 1.',
    waitingAmazon: 'Waiting for Amazon response...',
    saving: 'Saving…',
    resolveEligibility: 'Resolve eligibility in Amazon',
    retryStep1: 'Retry Step 1',
    waitingPlan: 'Waiting for Amazon plan',
    addUnits: 'Add units',
    continueToPacking: 'Continue to packing',
    step1Title: 'Step 1 - Confirmed inventory to send',
    skusConfirmedShort: 'SKUs confirmed ({count})',
    ignoredLinesShort: 'Ignored lines ({count})',
    closeAdd: 'Close add',
    addProduct: 'Add product',
    searchSkuAsinName: 'Search SKU / ASIN / product name',
    searchInventoryHint: 'Search in inventory and add product into this shipment request.',
    searchingInventory: 'Searching inventory...',
    noInventoryResults: 'No inventory results.',
    hiddenInRequest: 'Already in request (hidden)',
    noHiddenProducts: 'No hidden products in this request.',
    add: 'Add',
    shipFromLabel: 'Ship from',
    marketplaceDestinationCountry: 'Marketplace destination (Country)',
    addAllUnitsOneBox: 'Add all units to one box',
    tableSkuDetails: 'SKU details',
    tablePackingDetails: 'Packing details',
    tableInfoAction: 'Information / action',
    tableQuantityToSend: 'Quantity to send',
    tableServices: 'Services',
    waitingSkusAndShipments: 'Waiting for Amazon response for SKUs and shipments...',
    noSkusToDisplay: 'No SKUs to display.',
    storageLabel: 'Storage',
    optionIndividualUnits: 'Individual units',
    optionCasePacked: 'Case packed',
    optionSingleSkuPallet: 'Single SKU pallet',
    optionCreatePackingTemplate: 'Create packing template',
    labelOwner: 'Label owner',
    expirationDateRequired: 'Expiration date required',
    printSkuLabels: 'Print SKU labels',
    moreInputs: 'More inputs',
    rechecking: 'Rechecking...',
    recheckAssign: 'Recheck assign',
    templateLabel: 'Template',
    unitsPerBoxShort: 'Units/box',
    casePackUnitsPerBox: 'Case pack - Units/box',
    amazonNeedsPackageAttrs: 'Amazon needs product package attributes for this SKU.',
    sendProductAttrs: 'Send product attributes to Amazon',
    sending: 'Sending...',
    noChangesToSend: 'No changes to send.',
    completeProductDimensions: 'Complete product dimensions (L/W/H).',
    completeProductWeight: 'Complete product weight.',
    couldNotSendAttrs: 'Could not send attributes to Amazon.',
    boxes: 'Boxes',
    box: 'Box',
    units: 'Units',
    remove: 'Remove',
    assigned: 'Assigned',
    addService: '+ Add service',
    allServicesAdded: 'All services already added.',
    noBoxServicesSelected: 'No box services selected.',
    unit: 'Unit',
    qty: 'Qty',
    total: 'Total',
    boxDetailsStep1: 'Box details (Step 1)',
    putAllInOneBoxRo: 'Put everything in one box',
    ignored: 'Ignored',
    skuMissing: 'SKU: missing',
    blockedUntilSkuCompleted: 'Blocked until SKU is completed.',
    excludedFromStep1bShipping: 'This line is excluded from Step 1b and Shipping.',
    servicesLockedIgnored: 'Services locked for ignored line.',
    missingCompanyIdTemplate: 'Missing companyId in plan; cannot save template.',
    setNameOrUnitsTemplate: 'Set a name or units per box for the template.',
    unitsPerBoxGreaterThanZero: 'Units per box must be greater than 0 for case pack.',
    couldNotSaveTemplate: 'Could not save template.',
    prepareFbaItems: 'Prepare your FBA items',
    close: 'Close',
    prepGuidance: 'Prep guidance',
    useManufacturerBarcode: 'Use manufacturer barcode',
    choosePrepCategory: 'Choose prep category',
    selectPlaceholder: 'Select...',
    guidance: 'Guidance',
    notEligibleManufacturerBarcode: 'This SKU is not eligible to use manufacturer barcode for tracking.',
    eligibleManufacturerBarcode: 'This SKU can use manufacturer barcode.',
    useManufacturerBarcodeTracking: 'Use manufacturer barcode for tracking',
    cancel: 'Cancel',
    save: 'Save',
    fulfillmentStorageType: 'Fulfilment by Amazon storage type',
    choosePrintingFormat: 'Choose printing format',
    thermalPrinting: 'Thermal printing',
    standardFormats: 'Standard formats',
    widthMm: 'Width (mm)',
    heightMm: 'Height (mm)',
    printLabels: 'Print labels',
    downloading: 'Downloading…',
    downloadLabels: 'Download labels',
    couldNotRequestLabels: 'Could not request labels from Amazon.',
    labelRequestSentRetry: 'Label request sent to Amazon; try again in a few seconds if the PDF did not open.',
    missingDownloadUrlOrOperationId: 'Amazon response missing downloadUrl/operationId',
    couldNotDownloadLabels: 'Could not download Amazon labels.',
    couldNotLoadTemplates: 'Could not load packing templates.',
    packGroupsPreviewTitle: 'Pack groups preview (Step 1)',
    loadingGroupingAmazon: 'Loading grouping from Amazon…',
    noPackingGroupsYet: 'No packing groups yet. Continue to Step 1b or reload the plan.',
    groupedAboveNotice: 'Products are grouped above in the list by pack groups.',
    packN: 'Pack {index}',
    skusConfirmedToSendSummary: 'SKUs confirmed to send: {count} ({units} units)',
    noBoxesYet: 'No boxes yet.',
    totalSkus: 'Total SKUs',
    unitsBoxed: 'Units boxed',
    enterBoxContentsHint: 'Enter the box contents above and the box weights and dimensions below',
    boxWeightKg: 'Box weight (kg)',
    boxDimensionsCm: 'Box dimensions (cm)',
    addAnotherBoxDimension: '+ Add another box dimension',
    allItems: 'All items',
    singleBox: 'Single box',
    unassigned: 'Unassigned',
    packGroupN: 'Pack group {index}',
    itemsBelowPackedTogether: 'Items below can be packed together.',
    packingDetailsTitle: 'Packing details',
    templateName: 'Template name',
    templateNameExample: 'e.g. 12/box',
    type: 'Type',
    skuLabelShort: 'SKU',
    asinLabelShort: 'ASIN',
    stockLabelShort: 'Stock',
    ofWord: 'of',
    genericSkuLabel: 'SKU',
    weightKg: 'Weight (kg)',
    dimensionsCm: 'Dimensions (cm)',
    dimLcmPlaceholder: 'L (cm)',
    dimWcmPlaceholder: 'W (cm)',
    dimHcmPlaceholder: 'H (cm)',
    dimLPlaceholder: 'L',
    dimWPlaceholder: 'W',
    dimHPlaceholder: 'H',
    zeroPlaceholder: '0',
    zeroDecimalPlaceholder: '0.0',
    removeBoxNAria: 'Remove box {index}',
    removeBoxDimensionsNAria: 'Remove box dimensions {index}',
    packPrefix: 'pack',
    prep: 'Prep',
    noPrepNeeded: 'No prep needed',
    prepFragileGlass: 'Fragile/glass',
    prepLiquidsNonGlass: 'Liquids (non glass)',
    prepPerforatedPackaging: 'Perforated packaging',
    prepPowderPelletsGranular: 'Powder, pellets and granular',
    prepSmall: 'Small'
  },
  ro: {
    opDefaultIssue: 'Amazon a raportat o problemă pentru acest SKU. Verifică și încearcă din nou.',
    opMissingPrep: 'Lipsește categoria de pregătire (prep) pentru acest SKU. Selectează prep și retrimite.',
    opNotEligible: 'Acest produs nu este eligibil momentan pentru inbound pe marketplace-ul selectat.',
    validationMissingBoxes: 'Adaugă cel puțin o cutie pentru fiecare grup cu unități.',
    validationMissingAssignments: 'Distribuie toate unitățile în cutii (Assigned trebuie să fie egal cu Units).',
    validationMissingDims: 'Completează dimensiunile și greutatea pentru fiecare cutie.',
    validationEmptyBoxes: 'Unele cutii sunt goale. Elimină-le sau adaugă produse.',
    validationOverweight: 'Greutatea depășește limita de {kg} kg.',
    validationOversize: 'O dimensiune depășește limita de {cm} cm pentru o cutie care nu conține exact 1 unitate.',
    prepRequired: 'Pregătire necesară: {list}',
    prepSetNeeded: 'Pregătire setată: necesară',
    prepSetNone: 'Pregătire setată: nu este necesară',
    statusEligible: 'Eligibil',
    statusListingMissing: 'Listing lipsă',
    statusListingInactive: 'Listing inactiv',
    statusRestricted: 'Restricționat',
    statusUnknown: 'Necunoscut',
    statusReasonListingMissingDestination: 'Listing inexistent pe marketplace-ul destinație',
    statusReasonListingDiscoverable: 'Listing găsit cu status DISCOVERABLE (considerat eligibil)',
    readyToPack: 'Gata de ambalare',
    removeListing: 'Elimină listing',
    noBoxesAssignedYet: 'Nicio cutie alocată încă.',
    noServicesSelected: 'Niciun serviciu selectat.',
    notEligibleBanner: 'Unele produse nu sunt eligibile pentru marketplace-ul selectat.',
    inboundPlanNotReady: 'Planul inbound Amazon nu este pregătit. Reîncearcă Pasul 1 pentru regenerare.',
    operationIssuesTitle: 'Amazon a raportat probleme pentru unele SKU-uri:',
    planStillLoading: 'Planul Amazon încă se încarcă. Așteptăm SKU-urile/shipments generate.',
    ignoredLinesNotice: '{count} linie(linii) fără SKU au fost ignorate. Completează SKU dacă vrei să le incluzi.',
    noticeMissingSkuOnMarketplace: 'SKU fără listing pe marketplace {marketplace} ({list}). Verifică dacă există ca FBA.',
    completeBoxPlanning: 'Finalizează planificarea cutiilor înainte de continuare.',
    noUnitsWarning: 'Nu există unități de trimis. Setează cel puțin 1 unitate.',
    alertNotEligible: 'Unele SKU-uri nu sunt eligibile în Amazon; corectează și încearcă din nou.',
    alertPlanNotReady: 'Planul inbound Amazon nu este gata. Reîncearcă Pasul 1.',
    waitingAmazon: 'Se așteaptă răspunsul Amazon...',
    saving: 'Se salvează…',
    resolveEligibility: 'Rezolvă eligibilitatea în Amazon',
    retryStep1: 'Reîncearcă Pasul 1',
    waitingPlan: 'Se așteaptă planul Amazon',
    addUnits: 'Adaugă unități',
    continueToPacking: 'Continuă la împachetare',
    step1Title: 'Pasul 1 - Inventar confirmat pentru trimitere',
    skusConfirmedShort: 'SKU-uri confirmate ({count})',
    ignoredLinesShort: 'Linii ignorate ({count})',
    closeAdd: 'Închide adăugarea',
    addProduct: 'Adaugă produs',
    searchSkuAsinName: 'Caută SKU / ASIN / nume produs',
    searchInventoryHint: 'Caută în inventar și adaugă produsul în această cerere.',
    searchingInventory: 'Se caută în inventar...',
    noInventoryResults: 'Niciun rezultat în inventar.',
    hiddenInRequest: 'Deja în cerere (ascunse)',
    noHiddenProducts: 'Nu există produse ascunse în această cerere.',
    add: 'Adaugă',
    shipFromLabel: 'Expeditor',
    marketplaceDestinationCountry: 'Marketplace destinație (Țară)',
    addAllUnitsOneBox: 'Adaugă toate unitățile într-o cutie',
    tableSkuDetails: 'Detalii SKU',
    tablePackingDetails: 'Detalii împachetare',
    tableInfoAction: 'Informații / acțiune',
    tableQuantityToSend: 'Cantitate de trimis',
    tableServices: 'Servicii',
    waitingSkusAndShipments: 'Se așteaptă răspunsul Amazon pentru SKU-uri și shipment-uri...',
    noSkusToDisplay: 'Nu există SKU-uri de afișat.',
    storageLabel: 'Depozitare',
    optionIndividualUnits: 'Unități individuale',
    optionCasePacked: 'Case pack',
    optionSingleSkuPallet: 'Palet SKU unic',
    optionCreatePackingTemplate: 'Creează șablon de împachetare',
    labelOwner: 'Proprietar etichetă',
    expirationDateRequired: 'Data expirării este necesară',
    printSkuLabels: 'Printează etichete SKU',
    moreInputs: 'Mai multe inputuri',
    rechecking: 'Se reverifică...',
    recheckAssign: 'Reverifică alocarea',
    templateLabel: 'Șablon',
    unitsPerBoxShort: 'Unități/cutie',
    casePackUnitsPerBox: 'Case pack - Unități/cutie',
    amazonNeedsPackageAttrs: 'Amazon are nevoie de atributele pachetului pentru acest SKU.',
    sendProductAttrs: 'Trimite atributele produsului la Amazon',
    sending: 'Se trimite...',
    noChangesToSend: 'Nu există modificări de trimis.',
    completeProductDimensions: 'Completează dimensiunile produsului (L/l/H).',
    completeProductWeight: 'Completează greutatea produsului.',
    couldNotSendAttrs: 'Nu s-au putut trimite atributele la Amazon.',
    boxes: 'Cutii',
    box: 'Cutie',
    units: 'Unități',
    remove: 'Șterge',
    assigned: 'Alocate',
    addService: '+ Adaugă serviciu',
    allServicesAdded: 'Toate serviciile au fost deja adăugate.',
    noBoxServicesSelected: 'Nu există servicii de cutii selectate.',
    unit: 'Unitar',
    qty: 'Cant.',
    total: 'Total',
    boxDetailsStep1: 'Detalii cutii (Pasul 1)',
    putAllInOneBoxRo: 'Pune totul într-o singură cutie',
    ignored: 'Ignorat',
    skuMissing: 'SKU: lipsă',
    blockedUntilSkuCompleted: 'Blocat până la completarea SKU.',
    excludedFromStep1bShipping: 'Această linie este exclusă din Pasul 1b și Shipping.',
    servicesLockedIgnored: 'Servicii blocate pentru linia ignorată.',
    missingCompanyIdTemplate: 'Lipsește companyId în plan; șablonul nu poate fi salvat.',
    setNameOrUnitsTemplate: 'Setează un nume sau unități/cutie pentru șablon.',
    unitsPerBoxGreaterThanZero: 'Unitățile per cutie trebuie să fie mai mari ca 0 pentru case pack.',
    couldNotSaveTemplate: 'Nu s-a putut salva șablonul.',
    prepareFbaItems: 'Pregătește articolele FBA',
    close: 'Închide',
    prepGuidance: 'Ghid prep',
    useManufacturerBarcode: 'Folosește codul producătorului',
    choosePrepCategory: 'Alege categoria prep',
    selectPlaceholder: 'Selectează...',
    guidance: 'Ghidaj',
    notEligibleManufacturerBarcode: 'Acest SKU nu este eligibil pentru codul producătorului.',
    eligibleManufacturerBarcode: 'Acest SKU poate folosi codul producătorului.',
    useManufacturerBarcodeTracking: 'Folosește codul producătorului pentru tracking',
    cancel: 'Anulează',
    save: 'Salvează',
    fulfillmentStorageType: 'Tip stocare Fulfilment by Amazon',
    choosePrintingFormat: 'Alege formatul de printare',
    thermalPrinting: 'Printare termică',
    standardFormats: 'Formate standard',
    widthMm: 'Lățime (mm)',
    heightMm: 'Înălțime (mm)',
    printLabels: 'Printează etichete',
    downloading: 'Se descarcă…',
    downloadLabels: 'Descarcă etichete',
    couldNotRequestLabels: 'Nu s-au putut solicita etichetele de la Amazon.',
    labelRequestSentRetry: 'Cererea de etichete a fost trimisă; reîncearcă în câteva secunde dacă PDF-ul nu s-a deschis.',
    missingDownloadUrlOrOperationId: 'Răspuns Amazon fără downloadUrl/operationId',
    couldNotDownloadLabels: 'Nu s-au putut descărca etichetele Amazon.',
    couldNotLoadTemplates: 'Nu s-au putut încărca șabloanele.',
    packGroupsPreviewTitle: 'Previzualizare grupuri de împachetare (Pasul 1)',
    loadingGroupingAmazon: 'Se încarcă gruparea de la Amazon…',
    noPackingGroupsYet: 'Nu există încă packing groups. Continuă la Pasul 1b sau reîncarcă planul.',
    groupedAboveNotice: 'Produsele sunt grupate mai sus în listă după pack groups.',
    packN: 'Pachet {index}',
    skusConfirmedToSendSummary: 'SKU-uri confirmate pentru trimitere: {count} ({units} unități)',
    noBoxesYet: 'Nu există încă cutii.',
    totalSkus: 'Total SKU-uri',
    unitsBoxed: 'Unități în cutii',
    enterBoxContentsHint: 'Introdu conținutul cutiilor mai sus și greutățile/dimensiunile mai jos',
    boxWeightKg: 'Greutate cutie (kg)',
    boxDimensionsCm: 'Dimensiuni cutie (cm)',
    addAnotherBoxDimension: '+ Adaugă alt set de dimensiuni',
    allItems: 'Toate produsele',
    singleBox: 'Cutie unică',
    unassigned: 'Nealocat',
    packGroupN: 'Grup pachet {index}',
    itemsBelowPackedTogether: 'Produsele de mai jos pot fi împachetate împreună.',
    packingDetailsTitle: 'Detalii împachetare',
    templateName: 'Nume șablon',
    templateNameExample: 'ex. 12/cutie',
    type: 'Tip',
    skuLabelShort: 'SKU',
    asinLabelShort: 'ASIN',
    stockLabelShort: 'Stoc',
    ofWord: 'din',
    genericSkuLabel: 'SKU',
    weightKg: 'Greutate (kg)',
    dimensionsCm: 'Dimensiuni (cm)',
    dimLcmPlaceholder: 'L (cm)',
    dimWcmPlaceholder: 'l (cm)',
    dimHcmPlaceholder: 'H (cm)',
    dimLPlaceholder: 'L',
    dimWPlaceholder: 'l',
    dimHPlaceholder: 'H',
    zeroPlaceholder: '0',
    zeroDecimalPlaceholder: '0,0',
    removeBoxNAria: 'Elimină cutia {index}',
    removeBoxDimensionsNAria: 'Elimină dimensiunile cutiei {index}',
    packPrefix: 'pachet',
    prep: 'Prep',
    noPrepNeeded: 'Fără prep necesar',
    prepFragileGlass: 'Fragil/sticlă',
    prepLiquidsNonGlass: 'Lichide (fără sticlă)',
    prepPerforatedPackaging: 'Ambalaj perforat',
    prepPowderPelletsGranular: 'Pulbere, pelete și granule',
    prepSmall: 'Mic'
  },
  fr: {
    opDefaultIssue: 'Amazon a signalé un problème pour ce SKU. Vérifiez et réessayez.',
    opMissingPrep: 'La classification prep est manquante pour ce SKU. Sélectionnez-la et renvoyez.',
    opNotEligible: 'Ce produit n’est pas éligible à l’inbound sur la marketplace sélectionnée.',
    validationMissingBoxes: 'Ajoutez au moins une boîte pour chaque groupe avec des unités.',
    validationMissingAssignments: 'Répartissez toutes les unités dans les boîtes (Assigned = Units).',
    validationMissingDims: 'Ajoutez dimensions et poids pour chaque boîte.',
    validationEmptyBoxes: 'Certaines boîtes sont vides. Supprimez-les ou ajoutez des articles.',
    validationOverweight: 'Le poids dépasse la limite de {kg} kg.',
    validationOversize: 'Une dimension dépasse la limite de {cm} cm pour une boîte qui ne contient pas exactement 1 unité.',
    prepRequired: 'Préparation requise : {list}',
    prepSetNeeded: 'Préparation définie : requise',
    prepSetNone: 'Préparation définie : non requise',
    statusEligible: 'Éligible',
    statusListingMissing: 'Annonce manquante',
    statusListingInactive: 'Annonce inactive',
    statusRestricted: 'Restreint',
    statusUnknown: 'Inconnu',
    statusReasonListingMissingDestination: 'Annonce manquante sur la marketplace de destination',
    statusReasonListingDiscoverable: 'Annonce trouvée avec le statut DISCOVERABLE (considérée éligible)',
    readyToPack: 'Prêt à emballer',
    removeListing: 'Supprimer l’annonce',
    noBoxesAssignedYet: 'Aucune boîte assignée pour le moment.',
    noServicesSelected: 'Aucun service sélectionné.',
    notEligibleBanner: 'Certains produits ne sont pas éligibles pour la marketplace sélectionnée.',
    inboundPlanNotReady: 'Le plan inbound Amazon n’est pas prêt. Réessayez l’étape 1.',
    operationIssuesTitle: 'Amazon a signalé des problèmes pour certains SKU :',
    planStillLoading: 'Le plan Amazon est encore en cours de chargement.',
    ignoredLinesNotice: '{count} ligne(s) sans SKU ont été ignorées.',
    noticeMissingSkuOnMarketplace: 'SKU sans annonce sur la marketplace {marketplace} ({list}). Vérifiez qu’il existe en FBA.',
    completeBoxPlanning: 'Complétez le plan de boîtes avant de continuer.',
    noUnitsWarning: 'Aucune unité à envoyer. Définissez au moins 1 unité.',
    alertNotEligible: 'Certains SKU ne sont pas éligibles sur Amazon ; corrigez puis réessayez.',
    alertPlanNotReady: 'Le plan inbound Amazon n’est pas prêt. Réessayez l’étape 1.',
    waitingAmazon: 'En attente de la réponse Amazon...',
    saving: 'Enregistrement…',
    resolveEligibility: 'Résoudre l’éligibilité dans Amazon',
    retryStep1: 'Réessayer l’étape 1',
    waitingPlan: 'En attente du plan Amazon',
    addUnits: 'Ajouter des unités',
    continueToPacking: 'Continuer vers l’emballage',
    step1Title: 'Étape 1 - Inventaire confirmé à expédier',
    skusConfirmedShort: 'SKU confirmés ({count})',
    ignoredLinesShort: 'Lignes ignorées ({count})',
    closeAdd: 'Fermer l’ajout',
    addProduct: 'Ajouter un produit',
    searchSkuAsinName: 'Rechercher SKU / ASIN / nom produit',
    searchInventoryHint: 'Recherchez dans le stock et ajoutez le produit à cette demande.',
    searchingInventory: 'Recherche dans le stock...',
    noInventoryResults: 'Aucun résultat dans le stock.',
    hiddenInRequest: 'Déjà dans la demande (masqués)',
    noHiddenProducts: 'Aucun produit masqué dans cette demande.',
    add: 'Ajouter',
    shipFromLabel: 'Expéditeur',
    marketplaceDestinationCountry: 'Marketplace de destination (Pays)',
    addAllUnitsOneBox: 'Mettre toutes les unités dans une boîte',
    tableSkuDetails: 'Détails SKU',
    tablePackingDetails: 'Détails d’emballage',
    tableInfoAction: 'Information / action',
    tableQuantityToSend: 'Quantité à envoyer',
    tableServices: 'Services',
    waitingSkusAndShipments: 'En attente de la réponse Amazon pour les SKU et expéditions...',
    noSkusToDisplay: 'Aucun SKU à afficher.',
    storageLabel: 'Stockage',
    optionIndividualUnits: 'Unités individuelles',
    optionCasePacked: 'Case pack',
    optionSingleSkuPallet: 'Palette SKU unique',
    optionCreatePackingTemplate: 'Créer un modèle d’emballage',
    labelOwner: 'Propriétaire des étiquettes',
    expirationDateRequired: 'Date d’expiration requise',
    printSkuLabels: 'Imprimer les étiquettes SKU',
    moreInputs: 'Plus de champs',
    rechecking: 'Vérification...',
    recheckAssign: 'Revérifier l’affectation',
    templateLabel: 'Modèle',
    unitsPerBoxShort: 'Unités/boîte',
    casePackUnitsPerBox: 'Case pack - Unités/boîte',
    amazonNeedsPackageAttrs: 'Amazon exige les attributs de colis pour ce SKU.',
    sendProductAttrs: 'Envoyer les attributs produit à Amazon',
    sending: 'Envoi...',
    noChangesToSend: 'Aucun changement à envoyer.',
    completeProductDimensions: 'Complétez les dimensions produit (L/l/H).',
    completeProductWeight: 'Complétez le poids du produit.',
    couldNotSendAttrs: 'Impossible d’envoyer les attributs à Amazon.',
    boxes: 'Boîtes',
    box: 'Boîte',
    units: 'Unités',
    remove: 'Supprimer',
    assigned: 'Affectées',
    addService: '+ Ajouter un service',
    allServicesAdded: 'Tous les services ont déjà été ajoutés.',
    noBoxServicesSelected: 'Aucun service de boîte sélectionné.',
    unit: 'Unité',
    qty: 'Qté',
    total: 'Total',
    boxDetailsStep1: 'Détails des boîtes (Étape 1)',
    putAllInOneBoxRo: 'Mettre tout dans une seule boîte',
    ignored: 'Ignoré',
    skuMissing: 'SKU : manquant',
    blockedUntilSkuCompleted: 'Bloqué jusqu’à compléter le SKU.',
    excludedFromStep1bShipping: 'Cette ligne est exclue de l’étape 1b et du transport.',
    servicesLockedIgnored: 'Services verrouillés pour la ligne ignorée.',
    missingCompanyIdTemplate: 'companyId manquant dans le plan ; impossible de sauvegarder le modèle.',
    setNameOrUnitsTemplate: 'Définissez un nom ou des unités/boîte pour le modèle.',
    unitsPerBoxGreaterThanZero: 'Les unités par boîte doivent être supérieures à 0 pour case pack.',
    couldNotSaveTemplate: 'Impossible de sauvegarder le modèle.',
    prepareFbaItems: 'Préparer vos articles FBA',
    close: 'Fermer',
    prepGuidance: 'Guide prep',
    useManufacturerBarcode: 'Utiliser le code fabricant',
    choosePrepCategory: 'Choisir une catégorie prep',
    selectPlaceholder: 'Sélectionner...',
    guidance: 'Guide',
    notEligibleManufacturerBarcode: 'Ce SKU n’est pas éligible au code fabricant.',
    eligibleManufacturerBarcode: 'Ce SKU peut utiliser le code fabricant.',
    useManufacturerBarcodeTracking: 'Utiliser le code fabricant pour le suivi',
    cancel: 'Annuler',
    save: 'Enregistrer',
    fulfillmentStorageType: 'Type de stockage Fulfilment by Amazon',
    choosePrintingFormat: 'Choisir le format d’impression',
    thermalPrinting: 'Impression thermique',
    standardFormats: 'Formats standards',
    widthMm: 'Largeur (mm)',
    heightMm: 'Hauteur (mm)',
    printLabels: 'Imprimer les étiquettes',
    downloading: 'Téléchargement…',
    downloadLabels: 'Télécharger les étiquettes',
    couldNotRequestLabels: 'Impossible de demander les étiquettes à Amazon.',
    labelRequestSentRetry: 'Demande envoyée à Amazon ; réessayez dans quelques secondes si le PDF ne s’ouvre pas.',
    missingDownloadUrlOrOperationId: 'Réponse Amazon sans downloadUrl/operationId',
    couldNotDownloadLabels: 'Impossible de télécharger les étiquettes Amazon.',
    couldNotLoadTemplates: 'Impossible de charger les modèles d’emballage.',
    packGroupsPreviewTitle: 'Aperçu des groupes d’emballage (Étape 1)',
    loadingGroupingAmazon: 'Chargement du regroupement Amazon…',
    noPackingGroupsYet: 'Aucun groupe d’emballage pour le moment. Continuez à l’étape 1b ou rechargez le plan.',
    groupedAboveNotice: 'Les produits sont regroupés ci-dessus dans la liste par groupes d’emballage.',
    packN: 'Colis {index}',
    skusConfirmedToSendSummary: 'SKU confirmés à envoyer : {count} ({units} unités)',
    noBoxesYet: 'Aucune boîte pour le moment.',
    totalSkus: 'Total SKU',
    unitsBoxed: 'Unités en boîtes',
    enterBoxContentsHint: 'Saisissez le contenu des boîtes ci-dessus, puis poids et dimensions ci-dessous',
    boxWeightKg: 'Poids de la boîte (kg)',
    boxDimensionsCm: 'Dimensions de la boîte (cm)',
    addAnotherBoxDimension: '+ Ajouter une autre dimension de boîte',
    allItems: 'Tous les articles',
    singleBox: 'Boîte unique',
    unassigned: 'Non assigné',
    packGroupN: 'Groupe de colis {index}',
    itemsBelowPackedTogether: 'Les articles ci-dessous peuvent être emballés ensemble.',
    packingDetailsTitle: 'Détails d’emballage',
    templateName: 'Nom du modèle',
    templateNameExample: 'ex. 12/boîte',
    type: 'Type',
    skuLabelShort: 'SKU',
    asinLabelShort: 'ASIN',
    stockLabelShort: 'Stock',
    ofWord: 'sur',
    genericSkuLabel: 'SKU',
    weightKg: 'Poids (kg)',
    dimensionsCm: 'Dimensions (cm)',
    dimLcmPlaceholder: 'L (cm)',
    dimWcmPlaceholder: 'l (cm)',
    dimHcmPlaceholder: 'H (cm)',
    dimLPlaceholder: 'L',
    dimWPlaceholder: 'l',
    dimHPlaceholder: 'H',
    zeroPlaceholder: '0',
    zeroDecimalPlaceholder: '0,0',
    removeBoxNAria: 'Supprimer la boîte {index}',
    removeBoxDimensionsNAria: 'Supprimer les dimensions de la boîte {index}',
    packPrefix: 'colis',
    prep: 'Prep',
    noPrepNeeded: 'Aucun prep requis',
    prepFragileGlass: 'Fragile/verre',
    prepLiquidsNonGlass: 'Liquides (hors verre)',
    prepPerforatedPackaging: 'Emballage perforé',
    prepPowderPelletsGranular: 'Poudre, granulés et matières granuleuses',
    prepSmall: 'Petit'
  },
  de: {
    opDefaultIssue: 'Amazon hat ein Problem für diese SKU gemeldet. Prüfen und erneut versuchen.',
    opMissingPrep: 'Die Prep-Klassifizierung fehlt für diese SKU. Bitte auswählen und erneut senden.',
    opNotEligible: 'Dieses Produkt ist für Inbound auf dem gewählten Marktplatz derzeit nicht berechtigt.',
    validationMissingBoxes: 'Füge mindestens eine Box für jede Gruppe mit Einheiten hinzu.',
    validationMissingAssignments: 'Verteile alle Einheiten auf Boxen (Assigned muss Units entsprechen).',
    validationMissingDims: 'Füge Maße und Gewicht für jede Box hinzu.',
    validationEmptyBoxes: 'Einige Boxen sind leer. Entferne sie oder füge Artikel hinzu.',
    validationOverweight: 'Gewicht überschreitet das Limit von {kg} kg.',
    validationOversize: 'Ein Maß überschreitet das Limit von {cm} cm für eine Box ohne genau 1 Einheit.',
    prepRequired: 'Vorbereitung erforderlich: {list}',
    prepSetNeeded: 'Vorbereitung gesetzt: erforderlich',
    prepSetNone: 'Vorbereitung gesetzt: nicht erforderlich',
    statusEligible: 'Berechtigt',
    statusListingMissing: 'Listing fehlt',
    statusListingInactive: 'Listing inaktiv',
    statusRestricted: 'Eingeschränkt',
    statusUnknown: 'Unbekannt',
    statusReasonListingMissingDestination: 'Listing auf dem Ziel-Marktplatz fehlt',
    statusReasonListingDiscoverable: 'Listing mit Status DISCOVERABLE gefunden (als berechtigt angesehen)',
    readyToPack: 'Packbereit',
    removeListing: 'Listing entfernen',
    noBoxesAssignedYet: 'Noch keine Box zugewiesen.',
    noServicesSelected: 'Keine Services ausgewählt.',
    notEligibleBanner: 'Einige Produkte sind für den gewählten Marktplatz nicht berechtigt.',
    inboundPlanNotReady: 'Amazon Inbound-Plan ist nicht bereit. Schritt 1 erneut versuchen.',
    operationIssuesTitle: 'Amazon hat für einige SKUs Probleme gemeldet:',
    planStillLoading: 'Amazon-Plan wird noch geladen.',
    ignoredLinesNotice: '{count} Zeile(n) ohne SKU wurden ignoriert.',
    noticeMissingSkuOnMarketplace: 'SKU ohne Listing auf Marktplatz {marketplace} ({list}). Prüfe, ob es als FBA existiert.',
    completeBoxPlanning: 'Box-Planung vor dem Fortfahren abschließen.',
    noUnitsWarning: 'Keine Einheiten zum Senden. Mindestens 1 Einheit setzen.',
    alertNotEligible: 'Einige SKUs sind bei Amazon nicht berechtigt. Bitte korrigieren und erneut versuchen.',
    alertPlanNotReady: 'Amazon Inbound-Plan ist nicht bereit. Schritt 1 erneut versuchen.',
    waitingAmazon: 'Warte auf Amazon-Antwort...',
    saving: 'Speichern…',
    resolveEligibility: 'Berechtigung in Amazon lösen',
    retryStep1: 'Schritt 1 wiederholen',
    waitingPlan: 'Warte auf Amazon-Plan',
    addUnits: 'Einheiten hinzufügen',
    continueToPacking: 'Zum Packen weiter',
    step1Title: 'Schritt 1 - Bestätigter Bestand zum Versand',
    skusConfirmedShort: 'Bestätigte SKUs ({count})',
    ignoredLinesShort: 'Ignorierte Zeilen ({count})',
    closeAdd: 'Hinzufügen schließen',
    addProduct: 'Produkt hinzufügen',
    searchSkuAsinName: 'SKU / ASIN / Produktname suchen',
    searchInventoryHint: 'Im Bestand suchen und Produkt zu dieser Anfrage hinzufügen.',
    searchingInventory: 'Bestand wird durchsucht...',
    noInventoryResults: 'Keine Bestandsergebnisse.',
    hiddenInRequest: 'Bereits in Anfrage (ausgeblendet)',
    noHiddenProducts: 'Keine ausgeblendeten Produkte in dieser Anfrage.',
    add: 'Hinzufügen',
    shipFromLabel: 'Versand von',
    marketplaceDestinationCountry: 'Ziel-Marketplace (Land)',
    addAllUnitsOneBox: 'Alle Einheiten in eine Box',
    tableSkuDetails: 'SKU-Details',
    tablePackingDetails: 'Packdetails',
    tableInfoAction: 'Information / Aktion',
    tableQuantityToSend: 'Menge zum Versand',
    tableServices: 'Services',
    waitingSkusAndShipments: 'Warte auf Amazon-Antwort für SKUs und Sendungen...',
    noSkusToDisplay: 'Keine SKUs zum Anzeigen.',
    storageLabel: 'Lagerung',
    optionIndividualUnits: 'Einzelne Einheiten',
    optionCasePacked: 'Case Pack',
    optionSingleSkuPallet: 'Einzel-SKU-Palette',
    optionCreatePackingTemplate: 'Packvorlage erstellen',
    labelOwner: 'Label-Eigentümer',
    expirationDateRequired: 'Ablaufdatum erforderlich',
    printSkuLabels: 'SKU-Labels drucken',
    moreInputs: 'Weitere Eingaben',
    rechecking: 'Prüfe erneut...',
    recheckAssign: 'Zuweisung neu prüfen',
    templateLabel: 'Vorlage',
    unitsPerBoxShort: 'Einheiten/Box',
    casePackUnitsPerBox: 'Case Pack - Einheiten/Box',
    amazonNeedsPackageAttrs: 'Amazon benötigt Paketattribute für diese SKU.',
    sendProductAttrs: 'Produktattribute an Amazon senden',
    sending: 'Senden...',
    noChangesToSend: 'Keine Änderungen zum Senden.',
    completeProductDimensions: 'Produktmaße (L/B/H) vervollständigen.',
    completeProductWeight: 'Produktgewicht vervollständigen.',
    couldNotSendAttrs: 'Attribute konnten nicht an Amazon gesendet werden.',
    boxes: 'Boxen',
    box: 'Box',
    units: 'Einheiten',
    remove: 'Entfernen',
    assigned: 'Zugewiesen',
    addService: '+ Service hinzufügen',
    allServicesAdded: 'Alle Services wurden bereits hinzugefügt.',
    noBoxServicesSelected: 'Keine Box-Services ausgewählt.',
    unit: 'Einheit',
    qty: 'Menge',
    total: 'Gesamt',
    boxDetailsStep1: 'Boxdetails (Schritt 1)',
    putAllInOneBoxRo: 'Alles in eine einzige Box legen',
    ignored: 'Ignoriert',
    skuMissing: 'SKU: fehlt',
    blockedUntilSkuCompleted: 'Blockiert, bis SKU ergänzt ist.',
    excludedFromStep1bShipping: 'Diese Zeile ist von Schritt 1b und Versand ausgeschlossen.',
    servicesLockedIgnored: 'Services für ignorierte Zeile gesperrt.',
    missingCompanyIdTemplate: 'companyId im Plan fehlt; Vorlage kann nicht gespeichert werden.',
    setNameOrUnitsTemplate: 'Name oder Einheiten/Box für die Vorlage setzen.',
    unitsPerBoxGreaterThanZero: 'Einheiten pro Box müssen bei Case Pack größer als 0 sein.',
    couldNotSaveTemplate: 'Vorlage konnte nicht gespeichert werden.',
    prepareFbaItems: 'FBA-Artikel vorbereiten',
    close: 'Schließen',
    prepGuidance: 'Prep-Hinweis',
    useManufacturerBarcode: 'Herstellerbarcode verwenden',
    choosePrepCategory: 'Prep-Kategorie wählen',
    selectPlaceholder: 'Auswählen...',
    guidance: 'Hinweis',
    notEligibleManufacturerBarcode: 'Diese SKU ist für Herstellerbarcode nicht geeignet.',
    eligibleManufacturerBarcode: 'Diese SKU kann Herstellerbarcode verwenden.',
    useManufacturerBarcodeTracking: 'Herstellerbarcode für Tracking verwenden',
    cancel: 'Abbrechen',
    save: 'Speichern',
    fulfillmentStorageType: 'Fulfilment by Amazon Lagertyp',
    choosePrintingFormat: 'Druckformat wählen',
    thermalPrinting: 'Thermodruck',
    standardFormats: 'Standardformate',
    widthMm: 'Breite (mm)',
    heightMm: 'Höhe (mm)',
    printLabels: 'Labels drucken',
    downloading: 'Wird heruntergeladen…',
    downloadLabels: 'Labels herunterladen',
    couldNotRequestLabels: 'Labels konnten nicht bei Amazon angefordert werden.',
    labelRequestSentRetry: 'Label-Anfrage an Amazon gesendet; in einigen Sekunden erneut versuchen, falls PDF nicht öffnet.',
    missingDownloadUrlOrOperationId: 'Amazon-Antwort ohne downloadUrl/operationId',
    couldNotDownloadLabels: 'Amazon-Labels konnten nicht heruntergeladen werden.',
    couldNotLoadTemplates: 'Packvorlagen konnten nicht geladen werden.',
    packGroupsPreviewTitle: 'Packgruppen-Vorschau (Schritt 1)',
    loadingGroupingAmazon: 'Amazon-Gruppierung wird geladen…',
    noPackingGroupsYet: 'Noch keine Packgruppen. Mit Schritt 1b fortfahren oder Plan neu laden.',
    groupedAboveNotice: 'Produkte sind oben in der Liste nach Packgruppen gruppiert.',
    packN: 'Pack {index}',
    skusConfirmedToSendSummary: 'Bestätigte SKUs zum Versand: {count} ({units} Einheiten)',
    noBoxesYet: 'Noch keine Boxen.',
    totalSkus: 'Gesamt-SKUs',
    unitsBoxed: 'Einheiten in Boxen',
    enterBoxContentsHint: 'Boxinhalt oben eingeben, unten Gewichte und Maße',
    boxWeightKg: 'Boxgewicht (kg)',
    boxDimensionsCm: 'Boxmaße (cm)',
    addAnotherBoxDimension: '+ Weitere Boxmaße hinzufügen',
    allItems: 'Alle Artikel',
    singleBox: 'Einzelbox',
    unassigned: 'Nicht zugewiesen',
    packGroupN: 'Packgruppe {index}',
    itemsBelowPackedTogether: 'Die folgenden Artikel können zusammen verpackt werden.',
    packingDetailsTitle: 'Packdetails',
    templateName: 'Vorlagenname',
    templateNameExample: 'z. B. 12/Box',
    type: 'Typ',
    skuLabelShort: 'SKU',
    asinLabelShort: 'ASIN',
    stockLabelShort: 'Bestand',
    ofWord: 'von',
    genericSkuLabel: 'SKU',
    weightKg: 'Gewicht (kg)',
    dimensionsCm: 'Maße (cm)',
    dimLcmPlaceholder: 'L (cm)',
    dimWcmPlaceholder: 'B (cm)',
    dimHcmPlaceholder: 'H (cm)',
    dimLPlaceholder: 'L',
    dimWPlaceholder: 'B',
    dimHPlaceholder: 'H',
    zeroPlaceholder: '0',
    zeroDecimalPlaceholder: '0,0',
    removeBoxNAria: 'Box {index} entfernen',
    removeBoxDimensionsNAria: 'Boxmaße {index} entfernen',
    packPrefix: 'Pack',
    prep: 'Prep',
    noPrepNeeded: 'Kein Prep erforderlich',
    prepFragileGlass: 'Zerbrechlich/Glas',
    prepLiquidsNonGlass: 'Flüssigkeiten (ohne Glas)',
    prepPerforatedPackaging: 'Perforierte Verpackung',
    prepPowderPelletsGranular: 'Pulver, Pellets und Granulat',
    prepSmall: 'Klein'
  },
  it: {
    opDefaultIssue: 'Amazon ha segnalato un problema per questo SKU. Controlla e riprova.',
    opMissingPrep: 'Manca la classificazione prep per questo SKU. Selezionala e invia di nuovo.',
    opNotEligible: 'Questo prodotto non è idoneo all’inbound sul marketplace selezionato.',
    validationMissingBoxes: 'Aggiungi almeno una scatola per ogni gruppo con unità.',
    validationMissingAssignments: 'Distribuisci tutte le unità nelle scatole (Assigned deve essere uguale a Units).',
    validationMissingDims: 'Aggiungi dimensioni e peso per ogni scatola.',
    validationEmptyBoxes: 'Alcune scatole sono vuote. Rimuovile o aggiungi articoli.',
    validationOverweight: 'Il peso supera il limite di {kg} kg.',
    validationOversize: 'Una dimensione supera il limite di {cm} cm per una scatola che non contiene esattamente 1 unità.',
    prepRequired: 'Prep richiesto: {list}',
    prepSetNeeded: 'Prep impostato: richiesto',
    prepSetNone: 'Prep impostato: non richiesto',
    statusEligible: 'Idoneo',
    statusListingMissing: 'Listing mancante',
    statusListingInactive: 'Listing inattivo',
    statusRestricted: 'Limitato',
    statusUnknown: 'Sconosciuto',
    statusReasonListingMissingDestination: 'Listing mancante nel marketplace di destinazione',
    statusReasonListingDiscoverable: 'Listing trovato con stato DISCOVERABLE (considerato idoneo)',
    readyToPack: 'Pronto per l’imballaggio',
    removeListing: 'Rimuovi listing',
    noBoxesAssignedYet: 'Nessuna scatola assegnata.',
    noServicesSelected: 'Nessun servizio selezionato.',
    notEligibleBanner: 'Alcuni prodotti non sono idonei per il marketplace selezionato.',
    inboundPlanNotReady: 'Il piano inbound Amazon non è pronto. Riprova lo Step 1.',
    operationIssuesTitle: 'Amazon ha segnalato problemi per alcuni SKU:',
    planStillLoading: 'Il piano Amazon è ancora in caricamento.',
    ignoredLinesNotice: '{count} riga(e) senza SKU sono state ignorate.',
    noticeMissingSkuOnMarketplace: 'SKU senza listing sul marketplace {marketplace} ({list}). Verifica che esista come FBA.',
    completeBoxPlanning: 'Completa la pianificazione delle scatole prima di continuare.',
    noUnitsWarning: 'Nessuna unità da inviare. Imposta almeno 1 unità.',
    alertNotEligible: 'Alcuni SKU non sono idonei su Amazon; correggi e riprova.',
    alertPlanNotReady: 'Il piano inbound Amazon non è pronto. Riprova lo Step 1.',
    waitingAmazon: 'In attesa della risposta di Amazon...',
    saving: 'Salvataggio…',
    resolveEligibility: 'Risolvi idoneità in Amazon',
    retryStep1: 'Riprova Step 1',
    waitingPlan: 'In attesa del piano Amazon',
    addUnits: 'Aggiungi unità',
    continueToPacking: 'Continua al packing'
  },
  es: {
    opDefaultIssue: 'Amazon informó un problema para este SKU. Revísalo e inténtalo de nuevo.',
    opMissingPrep: 'Falta la clasificación prep para este SKU. Selecciónala y vuelve a enviar.',
    opNotEligible: 'Este producto no es apto para inbound en el marketplace seleccionado.',
    validationMissingBoxes: 'Añade al menos una caja para cada grupo con unidades.',
    validationMissingAssignments: 'Distribuye todas las unidades en cajas (Assigned debe ser igual a Units).',
    validationMissingDims: 'Añade dimensiones y peso para cada caja.',
    validationEmptyBoxes: 'Algunas cajas están vacías. Elimínalas o añade artículos.',
    validationOverweight: 'El peso supera el límite de {kg} kg.',
    validationOversize: 'Una dimensión supera el límite de {cm} cm para una caja que no contiene exactamente 1 unidad.',
    prepRequired: 'Preparación requerida: {list}',
    prepSetNeeded: 'Preparación configurada: requerida',
    prepSetNone: 'Preparación configurada: no requerida',
    statusEligible: 'Elegible',
    statusListingMissing: 'Listing faltante',
    statusListingInactive: 'Listing inactivo',
    statusRestricted: 'Restringido',
    statusUnknown: 'Desconocido',
    statusReasonListingMissingDestination: 'Listing inexistente en el marketplace de destino',
    statusReasonListingDiscoverable: 'Listing encontrado con estado DISCOVERABLE (considerado elegible)',
    readyToPack: 'Listo para preparar',
    removeListing: 'Eliminar listing',
    noBoxesAssignedYet: 'Aún no hay cajas asignadas.',
    noServicesSelected: 'No hay servicios seleccionados.',
    notEligibleBanner: 'Algunos productos no son elegibles para el marketplace seleccionado.',
    inboundPlanNotReady: 'El plan inbound de Amazon no está listo. Reintenta el Paso 1.',
    operationIssuesTitle: 'Amazon informó problemas para algunos SKU:',
    planStillLoading: 'El plan de Amazon todavía se está cargando.',
    ignoredLinesNotice: 'Se ignoraron {count} línea(s) sin SKU.',
    noticeMissingSkuOnMarketplace: 'SKU sin listing en el marketplace {marketplace} ({list}). Verifica si existe como FBA.',
    completeBoxPlanning: 'Completa la planificación de cajas antes de continuar.',
    noUnitsWarning: 'No hay unidades para enviar. Define al menos 1 unidad.',
    alertNotEligible: 'Algunos SKU no son elegibles en Amazon; corrige e inténtalo de nuevo.',
    alertPlanNotReady: 'El plan inbound de Amazon no está listo. Reintenta el Paso 1.',
    waitingAmazon: 'Esperando respuesta de Amazon...',
    saving: 'Guardando…',
    resolveEligibility: 'Resolver elegibilidad en Amazon',
    retryStep1: 'Reintentar Paso 1',
    waitingPlan: 'Esperando plan de Amazon',
    addUnits: 'Agregar unidades',
    continueToPacking: 'Continuar al empaquetado'
  }
};
